### DISCUSSION TITLE
How to handle gitmoji?

### DISCUSSION THREAD

**Discussion by TheAwiteb** [orhun/git-cliff#492] [Q&A]
Hello I have this git log
```log
bcae0bd (HEAD -> master) 🐛 (macos): Fix some issue with macos
4cf994d (tag: v0.0.2) 📝 Fix doc typo
56c9402 ♻ (cli): Refactor some code
e0d7ee7 (tag: v0.0.1) :bug: Fix the command line input (#18)
e98c4e1 ✨ Some what fetaure
```
As you can see I'am using [gitmoji specification](https://gitmoji.dev/specification) and this is my  `commit_parsers`
```toml
commit_parsers = [
  # Gitmoji
  {message = "^(✨|:sparkles:)", group = "✨ Feature"},
  {message = "^(🐛|:bug:)", group = "🐛 Bugfix"},
  {message = "^(♿️|:wheelchair:)", group = "♿️ Accessibility"},
  {message = "^(📝|:pencil:)", group = "📝 Documentation"},
  {message = "^(♻️|:recycle:)", group = "♻️ Refactor"},
  {message = "^(⬆️|➕|➖|⬇️|:arrow_up:|:heavy_plus_sign:|:heavy_minus_sign:|:arrow_down:)", group = "📦 Dependency"},
  {message = "^(🗑️|:wastebasket:)", group = "🗑️ Deprecation"},
  {message = "^(⚰️|:coffin:)", group = "⚰️ Remove"},
  {message = "^(🚨|:rotating_light:)", group = "🚨 Breaking Changes 🚨"},
  {message = "\\(macos\\):", group = "🍎 MacOS"},
  {message = "\\(windows\\):", group = "🪟 Windows"},
  {message = "\\(linux\\):", group = "🐧 Linux"},
]
```
This should work fine I guess, but when I run `git cliff` this is the output
```md
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## unreleased

### 🍎 MacOS

- (macos): Fix some issue with macos
 - ([bcae0bd](https://github.com/TheAwiteb/gitmoji-msg/commit/bcae0bd2f76e7e9f79367dac4a1ae5c3bb3cbcc9))

## [0.0.2](https://github.com/TheAwiteb/gitmoji-msg/compare/v0.0.1..v0.0.2) - 2024-02-10

## 0.0.1 - 2024-02-10

This changelog was generated by [git-cliff](https://github.com/orhun/git-cliff)
```

It's handled the scopes but not the gitmoji and I don't know why. What is wrong in my config?

<details>
<summary>My config file</summary>

```toml
[changelog]
# changelog header
header = """
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}](<REPO>/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## unreleased
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} - ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
This changelog was generated by [git-cliff](https://github.com/orhun/git-cliff)
"""
# postprocessors
postprocessors = [
  {pattern = '<REPO>', replace = "https://github.com/TheAwiteb/gitmoji-msg"}, # replace repository URL
]

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = false
# filter out the commits that are not conventional
filter_unconventional = false
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
  {pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"}, # replace issue numbers (Note the PR is also an issue in GitHub, so this will also link to PRs)
  {pattern = ' +$', replace = ""}, # Remove trailing whitespace.
  {pattern = ' +', replace = " "}, # Replace multiple spaces with a single space.
  {pattern = ' *(:\w+:|[\p{Emoji_Presentation}\p{Extended_Pictographic}](?:\u{FE0F})?\u{200D}?) *', replace = ""}, # Remove gitmoji, both actual UTF emoji and :emoji:
]
# regex for parsing and grouping commits
commit_parsers = [
  # Gitmoji
  {message = "^(✨|:sparkles:)", group = "✨ Feature"},
  {message = "^(🐛|:bug:)", group = "🐛 Bugfix"},
  {message = "^(♿️|:wheelchair:)", group = "♿️ Accessibility"},
  {message = "^(📝|:pencil:)", group = "📝 Documentation"},
  {message = "^(♻️|:recycle:)", group = "♻️ Refactor"},
  {message = "^(⬆️|➕|➖|⬇️|:arrow_up:|:heavy_plus_sign:|:heavy_minus_sign:|:arrow_down:)", group = "📦 Dependency"},
  {message = "^(🗑️|:wastebasket:)", group = "🗑️ Deprecation"},
  {message = "^(⚰️|:coffin:)", group = "⚰️ Remove"},
  {message = "^(🚨|:rotating_light:)", group = "🚨 Breaking Changes 🚨"},
  {message = "\\(macos\\):", group = "🍎 MacOS"},
  {message = "\\(windows\\):", group = "🪟 Windows"},
  {message = "\\(linux\\):", group = "🐧 Linux"},
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# regex for matching git tags
tag_pattern = "v[0-9]+\\.[0-9]+\\.[0-9]+"

# regex for skipping tags
skip_tags = ""
# regex for ignoring tags
ignore_tags = "v[0-9]+\\.[0-9]+\\.[0-9]+-(alpha|beta|rc)(\\.[0-9]+)?"
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42

```

</details>
