### DISCUSSION TITLE
Problem with bumping changelog

### DISCUSSION THREAD

**Discussion by devsheva** [orhun/git-cliff#800] [Q&A]
I'm trying to generate a new whole changelog with already present a first tag. 

I tried doing 
- `git cliff -o` --> leads to a changelog with all commits under unreleased
- `git cliff --bump -o` --> leads to a changelog with all commits under next tag

Context: already present a 1.0.0 tag

My goal is to achieve a changelog like:

```md
# Changelog

All notable changes to this project will be documented in this file.

## [1.0.1] - <date>

....

## [1.0.0] - <date>
....

```

**Comment by orhun** [comment]
Hello!

> git cliff --bump -o --> leads to a changelog with all commits under next tag

Yup, that's the correct usage. Is the problem that you're not getting the next tag you're expecting?

**Reply by devsheva** [reply]
I'm expecting what i put in the snippet. Both commands that i described don't help me to achieve that behaviour

**Reply by orhun** [reply]
can you share the output of `git cliff --bump`?

**Reply by devsheva** [reply]
As you can see the first tag 1.0.0-alpha gets lost
```md
# Changelog

All notable changes to this project will be documented in this file.

## [1.0.0-alpha.1] - 2024-08-18

### 🚀 Features

- Add preference to bot setup
- Add webhook endpoint for bot integration with Oak framework
- *(analysis)* Send message to user
- Add daily analysis cron job
- *(supabase)* Add test schema support
- Add supabase as storage for preferences
- *(analysis)* Respond with filtered story titles based on user preferences
- *(gemini-adapter)* Add responseSchema for storyIds
- *(gemini-adapter)* Replace with v1beta API and add responseMimeType on config
- *(gemini-adapter)* Implement generateContent call with response parsing
- Add changelog
- Deploy workflow
- Validate Item schema
- [**breaking**] Complete deno migration by fixing last tests
- Add list preferences cmd
- [**breaking**] Replace jest with vitest cause of esm troubles
- Reset preferences and fix convo loop
- Store preferences in session with conversations
- Ask for preference
- Determine session adapter in bot setup
- Get storage adapter for env
- Remove axios to use builtin fetch API
- Get 500 top stories

### 🐛 Bug Fixes

- Ignore any type lint error
- *(utils)* Type generic supabaseAdapter
- Correctly type users preferences group
- *(config)* Restore test task arg when setting env
- Add missing test variables for coverage
- Remove env leaking log
- Change root to cwd
- Import new types in bot.ts
- Adapt for deno deploy
- Use test flag on test task to retrieve right env file
- Remove overkilling functions and declare adapters inside always condition
- Disable noEmit during build
- Add ESM support for jest
- Remove ts-node and use tsx with watch mode

### 🚜 Refactor

- Update test_helpers.ts to use arrow function syntax
- Remove webhook task from deno.jsonc
- *(analysis)* Import bot dynamically
- *(gemini-adapter)* Simplify body object gen
- Improve env loading with zod
- [**breaking**] Move types in a single declaration file
- Add generic slashCommand generator

### 📚 Documentation

- Add instructions to run tests with test schema
- Force env variable setup
- Removed setMyCommands tip since an issue has been opened for it(#13)
- Fix typo on README
- Sort commits by newest for git-cliff
- Prioritize testing over styling in changelog
- Add deployment section
- Move codefactor badge on top
- Add codefactor badge
- Add todo for clear preferences and update readme with BDD tips
- Update readme with right usage of jest object
- Add setMyCommands usage tip
- Add testing guideline
- Update README with test instructions
- Add usage instructions

### 🧪 Testing

- Disable any lint
- *(helpers)* Cleanup database sessions
- *(analysis)* Add promisify factory with item mocks
- Stub global fetch
- [**breaking**] Fix specs adapting to vitest
- It responds to setup command
- Add type checkers
- Add faker and mock array of top stories
- Should return null for not found item
- Mock getItem api
- Add watch flag

### 🎨 Styling

- Remove unused no-explicit-any in spec
- Set editor.tabSize on 2
- Underscore file names
- Fix fmt of api.ts
- Add develop codefactor
- Add newline on heading

### ⚙️ Miscellaneous Tasks

- Skip changelog commits for git-cliff
- Add webhook listener to Oak app
- Update entrypoint to "src/webhook.ts" for deploying hn-telegram-bot
- Update deno version to 1.45.5
- Add closed pull request trigger to deploy workflow
- Remove dependabot 
- Add dependabot
- Skip dailyAnalysis  in test suite
- Update deno test command to remove watch flag
- Update deploy dev actions with supabase variables
- Update config.ts to load environment variables with export option
- *(analysis)* Parse user preferences and filter their stories
- Correctly type all parts using ramda
- Add deno check task to improve code quality
- *(types)* Type getUserPreferences
- *(ramda)* Add @types/ramda
- Remove any type from custom schemas in utils.ts
- Upgrade @std/testing to major 1
- Fix supabase deps
- Upgrade deno to 1.45.4 and include unstable cron
- *(analysis)* Get users preferences and seed db
- Add supabase secrets
- *(supabase)* Add db types and client connection
- Update changelog
- *(utils)* Add mapIndexed fn
- *(analysis)* Add error tests todo for __bulkRetrieveItems__
- *(analysis)* Bulk retrieve top stories as items with parallel requests
- *(gemini-adapter)* Add body builder function
- *(ai-adapter)* Add body call signature
- *(ai-adapter)* Add buildBody method
- *(gemini-adapter)* Init apiKey and baseUrl
- *(ai-adapter)* Rename text to input as generateContent param
- *(ai-adapter)* Init base adapter
- Upgrade deno to 1.45.1
- *(analysis)* Init folder structure
- *(gemini-response)* Add zod types for request and response schema of `generateContent` api
- Point ramda package to deno instead of nest
- AllowBreaking on updater
- Add format and lint job
- Ignore any lint in specs
- Cache dependencies during test
- Upgrade grammy to 1.27 with latest types
- Reignore .env.test
- Upgrade packages
- Manual update workflow
- Add update workflow
- Add codecov
- Add test job dependency
- Do not ignore .env test
- Add zod package
- Add coverage task
- Add recommended deno ext
- [**breaking**] Add grammy from deno
- [**breaking**] Add faker deno module
- [**breaking**] Add ramda external dep
- [**breaking**] Add deno and remove type definitions and tsconfig
- Add dependabot
- Upgrade dotenvx to major 1
- [**breaking**] Remove export of bot and use bot.ts as entrypoint
- Upgrade typescript npm
- Upgrade grammy
- Add todo on mocking api calls
- Upgrade grammy
- Init conversation plugin
- Remove some types and cleanup config
- Init setup composer
- [**breaking**] Use bot.ts as entrypoint
- Init grammy bot
- Replace telegraf with grammY
- Add tsconfig.build for excluding specs on compilation
- Remove error test
- Improve item typing for req
- Config jest to match only __tests__ folder
- Config jest for ts and move to src folder
- Move env declaration at root
- Add support of dotenvx
- Add build script for npm to run tsc
- Extend ProcessEnv of node with BOT_TOKEN
- Init project

### Deno

- Update imports
- Update imports

### Release

- *(1.0.0-alpha)* Bump changelog

<!-- generated by git-cliff -->
```

**Reply by orhun** [reply]
Can you also share the contents of `cliff.toml`? Let's make sure that they are not skipped via `skip_tags` or any other config option.

**Reply by devsheva** [reply]
```toml

# git-cliff ~ default configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organized into tables and keys.
# See documentation for more information on available options.

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
# template for the changelog footer
footer = """
<!-- generated by git-cliff -->
"""
# remove the leading and trailing s
trim = true
# postprocessors
postprocessors = [
  # { pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" }, # replace repository URL
]

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
  # Replace issue numbers
  #{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
  # Check spelling of the commit with https://github.com/crate-ci/typos
  # If the spelling is incorrect, it will be automatically fixed.
  #{ pattern = '.*', replace_command = 'typos --write-changes -' },
]
# regex for parsing and grouping commits
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^docs: update changelog", skip = true },
  { message = "^docs", group = "<!-- 3 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
  { message = "^style", group = "<!-- 6 -->🎨 Styling" },
  { message = "^test", group = "<!-- 5 -->🧪 Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# regex for matching git tags
# tag_pattern = "[0-9].*"
# regex for skipping tags
# skip_tags = ""
# regex for ignoring tags
# ignore_tags = ""
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "newest"
# limit the number of commits included in the changelog.
# limit_commits = 42

```
