### DISCUSSION TITLE
How to skip changelog commit in changelog

### DISCUSSION THREAD

**Discussion by RWOverdijk** [orhun/git-cliff#956] [Q&A]
Hi! I got everything up and running, I just noticed something that I find interesting:

`chore(release): create changelog for 0.2.3`

This is included in the changelog itself. It's not wrong, it did happen, but I think it can be skipped from the changelog itself.

Is it possible to prevent the changelog commit from being added to the changelog? 😄

**Comment by orhun** [comment]
Hello, sorry for the late reply.

For sure:

```toml
[git]
# regex for parsing and grouping commits
commit_parsers = [
  { message = "^chore\\(release\\): create changelog for", skip = true }
}
```
