### ISSUE TITLE
Any conventional commit results in a PATCH version, not just fix

### ISSUE THREAD

**Issue by S-Scholz** [orhun/git-cliff#1020]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

First of: thanks for this project. When I tried to integrate it to calculate the next release version based on the commits I ran into the following problem:

Adding _any_ conventional commit to the history results in a patch increase of the version, when `git-cliff ---bump` is used.

- Is this intended?
- If that is so, can this be configured in anyway?

### Steps To Reproduce

The following history works as expected, and produces `v0.1.0` via `git-cliff --bumped-version`

```
8e33455 (HEAD -> master) another commit
f1990f3 feat: a commit
306b48a (tag: v0.0.0) init commit
```

Adding the new tag and a commit that is not `fix|feat`:
```
da805b7 (HEAD -> master) ci: should not create a patch
8e33455 (tag: v0.1.0) another commit
f1990f3 feat: a commit
306b48a (tag: v0.0.0) init commit
```
Results in version of `v0.1.1`. Same behaviour for e.g. `docs: add readme`.

Additionally, adding the following settings to the default `cliff.toml`:
```
...
[bump]
custom_major_increment_regex = "major"
custom_minor_increment_regex = "minor|more"
```
Does not affect this behaviour.

### Expected behavior

As per the documentation (https://git-cliff.org/docs/usage/bump-version)

>    "fix:" -> increments PATCH
>   "feat:" -> increments MINOR
>   "scope!" (breaking changes) -> increments MAJOR

I would expect that, a patch version should only be created if there is a  `fix: ...` commit in the unreleased history. The following history should not create a patch increase.
```
da805b7 (HEAD -> master) ci: should not create a patch
8e33455 (tag: v0.1.0) another commit
f1990f3 feat: a commit
306b48a (tag: v0.0.0) init commit
```

However, a new patch version is created:
```
$ git cliff --bump --context | jq '.[0].version'
"v0.1.1"
```

### Software information

- Operating system: debian
- Project version: 2.7.0 (pre-compiled)

### Additional context

cliff.toml:
```toml
[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true
postprocessors = [ ]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"

[bump]
custom_major_increment_regex = "major"
custom_minor_increment_regex = "minor|more"
```
