### ISSUE TITLE
"Repository is not owned by current user" after lastest commit for #108

### ISSUE THREAD

**Issue by ChrisB9** [orhun/git-cliff#109]
**Describe the bug**
ERROR git_cliff > Git error: `repository path '/builds/project/path is not owned by current user; class=Config (7); code=Owner (-36)`

The error is caused by the change of directory and ownership + enabling safe directory in the Dockerfile by default in https://github.com/orhun/git-cliff/commit/4fc2217868fceea81ab5e6aeeb63ca719a07fe91 

**To Reproduce**

Using the following gitlab.yml configuration:
```
changelog:
  stage: changelog
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
```

**Expected behavior**
I know I am taking the risky path here and following the `latest` tag.
This is more of an informative bug report, but I believe this should have continued to work, as we automatically add the directory to the safe property of git.
Am I missing something here?

**System (please complete the following information):**
 - Docker: orhunp/git-cliff:latest from yesterday
