### ISSUE TITLE
using --latest flag always detects new contributors (that are not new)

### ISSUE THREAD

**Issue by mibelbahri** [orhun/git-cliff#1096]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

Hello team

I have a bug with git cliff, when using it to generate the release body, I always have new contributors popping, even if they have been contributing for a while.
 

### Steps To Reproduce

I run this to draft the release (in a github workflow):
```
 git cliff \
 -vv --latest --unreleased --strip all -o CHANGES.md \
 --github-repo ${{ github.repository }} \
 --github-token ${{ secrets.GITHUB_TOKEN }} \
 --tag ${{ inputs.tag }}
```

### Expected behavior

Expected behavior is to detect new contributors, only when there are new contributors

### Screenshots / Logs

N/A

### Software information

I run the latest version of git cliff in my github actions (github runner: ubuntu latest)

### Additional context

The command for changelog with the same config works fine.

```
git cliff \
 --verbose --strip 'footer' -o CHANGELOG.md \
 --github-repo ${{ github.repository }} \
 --github-token ${{ secrets.GITHUB_TOKEN }} \
 --tag ${{ inputs.tag }}
```

Thank you very much for your help

**Comment by orhun** [comment]
Hmm, interesting. My first thought about this was we were not missing all the data from GitHub thus our logic ends up putting everyone as a first contributor in the changelog. 

Running this locally, I see that's not the problem and I can't reproduce. Can you share more info about the changelog you are getting?

For more context, see #363 for how the remote integration works.

> I'm using the REST API for the current implementation and I'm fetching all the commits and pull requests. This sounds suboptimal but unfortunately we need all the commits to generate the required release context. For example:
> 
> git cliff -u: only generates the changelog for the unreleased changes. If we want to have a section there as "first contributors" then we need the whole commit/PR history to check if the user has contributed before. Unfortunately GitHub contributors API does not give us the SHA1 of the commits that belong to the contributors so I'm using the pull requests API.

**Comment by roflmuffin** [comment]
I am experiencing this, but with a simpler setup of just passing the tag that is about to be created to `git cliff`. 

For example, my git log has a commit with tag `v1.0.3` and then a bunch of changes after that. If I create a new tag on the current commit with `v1.0.4` those changes get accumulated properly and no new contributors are added. However if I do the same thing but instead of creating the tag, use `git cliff -t v1.0.4`, the same change set is generated but the contributors are listed as new.

**Comment by tsutsu3** [comment]
I'm experiencing the same issue in my environment using GitHub Actions.Both Dependabot and I are being recognized as new contributors, even though we've contributed before.

For reference, the `latest` flag is not being used in our workflow.

here is the workflow I'm currently using:
```yml
     - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --tag $VERSION_NAME a547cf240dd36443a9a00eb38c0ecc6e8acfd963..
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
