### ISSUE TITLE
Sub categories in changelog

### ISSUE THREAD

**Issue by syedelec** [orhun/git-cliff#122]
**Is your feature request related to a problem? Please describe.**
No issue

**Describe the solution you'd like**
Having the ability to provide sub categories to changelog, see example

**Describe alternatives you've considered**
I am not sure the best approach

**Additional context**
I am using a repo with multiple board support (e.g` common`, `board1` and `board2`) where `common` are the changes to both/general, `board1` are specific changes to the support of board 1 and `board2` are specific changes to the support of board 2.

I would like my changelog to be classified depending on the commit.

For example: 

board1: feat(hardware): add spi support
board2: fix(cloud): use gcp instead of azure
common: test(security): add selinux test suite

The output should be something like:

# Changelog

All notable changes to this project will be documented in this file.

#### Features

- *(hardware)* add spi support

#### Bug Fixes

- *(cloud)* use gcp instead of azure

#### Testing

- *(security)* add selinux test suite

#### Features

- *(...)* ...

#### Bug Fixes

- *(...)* ...

#### Testing

- *(...)* ...

**Comment by orhun** [comment]
Hello @syedelec,

Doing this is possible via [commit_preprocessors](https://github.com/orhun/git-cliff#commit_preprocessors):

```toml
commit_preprocessors = [
    { pattern = '(\w+): (\w+)\((\w+)\): (.*)', replace = "${2}(${1}): ($3) $4"},
]
```

So that your commits will be parsed as conventional.

You can use the following config:

<details>
<summary>Config</summary>

```toml
# configuration file for git-cliff (0.1.0)

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="scope") %}
    ### {{ group | upper_first }}
    {% for group, commits in commits | group_by(attribute="group") %}
        #### {{ group | upper_first }}
        {% for commit in commits %}
            - {{ commit.message | upper_first }}\
        {% endfor %}
    {% endfor %}\
{% endfor %}\n
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
    { pattern = '(\w+): (\w+)\((\w+)\): (.*)', replace = "${2}(${1}): ($3) $4"},
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^doc", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Refactor"},
    { message = "^style", group = "Styling"},
    { message = "^test", group = "Testing"},
    { message = "^chore\\(release\\): prepare for", skip = true},
    { message = "^chore", group = "Miscellaneous Tasks"},
    { body = ".*security", group = "Security"},
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# regex for skipping tags
skip_tags = "v0.1.0-beta.1"
# regex for ignoring tags
ignore_tags = ""
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
```

</details>

Output:

```
# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### Board1

#### Features

- (hardware) add spi support

### Board2

#### Bug Fixes

- (cloud) use gcp instead of azure

### Common

#### Testing

- (security) add selinux test suite

<!-- generated by git-cliff -->
```

I hope this helps! 🐻
