### ISSUE TITLE
PyProject not read 

### ISSUE THREAD

**Issue by carstencodes** [orhun/git-cliff#156]
**Pyproject not read**

**To reproduce**

Copy `changelog` and `git` from [.gitcliff.toml](https://github.com/carstencodes/pdm-bump/blob/c562f8a51edcd728da97f0b32910622c8a637761/.gitcliff.toml) to [pyproject.toml](https://github.com/carstencodes/pdm-bump/blob/c562f8a51edcd728da97f0b32910622c8a637761/pyproject.toml) and prepend `tool.gitcliff` to the toml section.

Run `git cliff` instead of `git cliff --config .gitcliff.toml`

**Expected behavior**

Output is same

**Screenshots / Logs**

`git cliff --config .gitcliff.toml -- v0.6.11...v0.7.0` 

```markdown
# Changelog

All notable changes to this project will be documented in this file.

##  Changelog for release 0.7.0
Released on 2023-04-14


### Bug Fixes

- Removed typo by Carsten Igel [06ea061](https://github.com/carstencodes/pdm-bump/commit/06ea06163ab306bbd2bbaf2993e873efb181c74f)
- Do not double define dict by Carsten Igel [cd24396](https://github.com/carstencodes/pdm-bump/commit/cd24396ebb222d299b7659af7a16b8899ba14f7f)
- Removed double argument by Carsten Igel [cf9ddc1](https://github.com/carstencodes/pdm-bump/commit/cf9ddc151b9f334649f38d23142a0c326d954930)

### Features

- Added auto-loading by Carsten Igel [a2ce4b3](https://github.com/carstencodes/pdm-bump/commit/a2ce4b3349670fb5e9e3132f1defa9371889bd27)
- Enabled verbose logging by Carsten Igel [67a751b](https://github.com/carstencodes/pdm-bump/commit/67a751baeb09c50fac081cb6017acfffdd01626c)
- Improved changelog generation by Carsten Igel [5412123](https://github.com/carstencodes/pdm-bump/commit/54121231713e9c3e9c6d4b524dd6bca904978854)
- Finalize explicit version setting by Carsten Igel [0233d16](https://github.com/carstencodes/pdm-bump/commit/0233d162b234a0082df6434eb7bc4cfeb79b9d69)

### Miscellaneous Tasks

- Updated 2 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [947ab77](https://github.com/carstencodes/pdm-bump/commit/947ab7761b2ffea42959e8de51f4b6abd8d375b2)
- Updated 2 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [63dbb2a](https://github.com/carstencodes/pdm-bump/commit/63dbb2abdb1999e17e401732f71e53f13377c0e3)
- Updated alpha version by Carsten Igel [9373609](https://github.com/carstencodes/pdm-bump/commit/9373609b17b487f90b3f5b3d2d6ee31825c3476e)
- Refactor allowed parameters by Carsten Igel [d7079f8](https://github.com/carstencodes/pdm-bump/commit/d7079f8fced14c489cb729df0e60ff3130651f64)
- Refactored argument creation by Carsten Igel [5d3c94b](https://github.com/carstencodes/pdm-bump/commit/5d3c94bcb85e940cbc9f299039d63d84e6802ce4)
- Applied format by Carsten Igel [eaa11dc](https://github.com/carstencodes/pdm-bump/commit/eaa11dcf010254b377a771d2622d6519022427bc)
- Pulled attributes up by Carsten Igel [8f8d784](https://github.com/carstencodes/pdm-bump/commit/8f8d78454b7348f151b1782a3ec9caaa9a4e212c)
- Renamed factory by Carsten Igel [544fee7](https://github.com/carstencodes/pdm-bump/commit/544fee758ddf46d76710a63a7b1cec1da9aa9afe)
- Loader instance will be final by Carsten Igel [3280669](https://github.com/carstencodes/pdm-bump/commit/3280669c974961b3437d01e7f3bd5edd6e15d796)
- Added configuration after PDM update by Carsten Igel [3db34aa](https://github.com/carstencodes/pdm-bump/commit/3db34aa1bf52833715ba885810e256f3e420cb98)
- Prepare next alpha by Carsten Igel [7f09b0f](https://github.com/carstencodes/pdm-bump/commit/7f09b0f59cd3da7da5889ce99750db1b2885e887)
- Prepare release by Carsten Igel [535df8d](https://github.com/carstencodes/pdm-bump/commit/535df8d1aad3c42a2dcb4e6f8dd6e7452eeb3122)

### Testing

- Modified imports from extension commands by Carsten Igel [6c3b01a](https://github.com/carstencodes/pdm-bump/commit/6c3b01a03c8d2f11fa3a40698c66bbe87206ae36)


**Full changelog**: [v0.7.0a1...v0.7.0](https://github.com/carstencodes/pdm-bump/compare/v0.7.0a1...v0.7.0)


##  Changelog for release 0.7.0a1
Released on 2023-04-10


### Bug Fixes

- Ignore arguments from pdm by Carsten Igel [c3808c9](https://github.com/carstencodes/pdm-bump/commit/c3808c99b20032cbbd9539bd0a4fd7b932c41de9)
- Types are not returned by Carsten Igel [90563b4](https://github.com/carstencodes/pdm-bump/commit/90563b40913211e04e53c36833000f098da4dbb3)

### Build recipes

- Added autoflake to formatters by Carsten Igel [5eb8b68](https://github.com/carstencodes/pdm-bump/commit/5eb8b68f61cfe3cd81afaa34d5bef04911ceb63c)
- Set fixed revision by Carsten Igel [278d045](https://github.com/carstencodes/pdm-bump/commit/278d0457207e04aabe1e08db073c004b01f69fcd)
- Added Automatic update by Carsten Igel [e79fc19](https://github.com/carstencodes/pdm-bump/commit/e79fc198808e62451ba7d237d550945092e6faab)
- Repaired auto-complete workflow by Carsten Igel [2305f2f](https://github.com/carstencodes/pdm-bump/commit/2305f2f9fe4e653df228a728feda778e6c6944a5)
- Repaired auto-complete workflow by Carsten Igel [f69c0f0](https://github.com/carstencodes/pdm-bump/commit/f69c0f0ce8850bdf6112045123cc559b0ef57802)
- Fixed auto update by Carsten Igel [95e4c4b](https://github.com/carstencodes/pdm-bump/commit/95e4c4b4a36734333daccc2e6a089716ad8b8ef2)
- Fixed auto update by Carsten Igel [1f66c58](https://github.com/carstencodes/pdm-bump/commit/1f66c585821fd852bcce79c13f4780c30ad38c14)
- Fix gitlint error during update by Carsten Igel [241ed86](https://github.com/carstencodes/pdm-bump/commit/241ed86d6c1995fc1d3ab5fa2e68c23c089c5214)
- Fix gitlint error during update by Carsten Igel [52a705d](https://github.com/carstencodes/pdm-bump/commit/52a705d86c1cb376864106bc3682d125af9fe797)
- Set job names by Carsten Igel [f32fea7](https://github.com/carstencodes/pdm-bump/commit/f32fea76d2a48b300c7108fd97351f685f7a98da)
- Added clean-up routine by Carsten Igel [d387145](https://github.com/carstencodes/pdm-bump/commit/d3871455345fd6e1104727a67a24d64632cd5d38)
- Add clean-up script by Carsten Igel [e05588a](https://github.com/carstencodes/pdm-bump/commit/e05588a880a3bd1fd2c805bc7fcce95c6b2a8946)

### Features

- Added actions package by Carsten Igel [c55d133](https://github.com/carstencodes/pdm-bump/commit/c55d133c83c19d06479ba7a43977364f89ac4817)
- Added ability to set version explicitly by Carsten Igel [bd9c9c3](https://github.com/carstencodes/pdm-bump/commit/bd9c9c31cd50cf85ab805fa7eeb46fe0a83099ad)
- Added ability to set version explicitly by Carsten Igel [5dc1d6c](https://github.com/carstencodes/pdm-bump/commit/5dc1d6ccbb9e1a1068fc5834eed1785482ca7957)

### Miscellaneous Tasks

- Updated settings by Carsten Igel [dca8dc4](https://github.com/carstencodes/pdm-bump/commit/dca8dc4bb31c777e3b3c64ffa2d5b102ec8f886a)
- Update dependencies by Carsten Igel [22c6d39](https://github.com/carstencodes/pdm-bump/commit/22c6d39ba04c209c23b31d5d782b50c8da3255c7)
- Use PDM 2.4.7 by Carsten Igel [257a023](https://github.com/carstencodes/pdm-bump/commit/257a023d728b6c254223953c6f4f0c26b43bfafe)
- Development version by Carsten Igel [6d6552c](https://github.com/carstencodes/pdm-bump/commit/6d6552c8d1e54d0795212f3efd1de1e8bf3ba424)
- Fixed linter by Carsten Igel [f504959](https://github.com/carstencodes/pdm-bump/commit/f50495987985cb9e0e6b408b1cc739a4f3cfc921)
- Update linter rule by Carsten Igel [dd9a966](https://github.com/carstencodes/pdm-bump/commit/dd9a966a759b7abc6e669e021e737ad95a6409a7)
- Pacify linter by Carsten Igel [d9cc01f](https://github.com/carstencodes/pdm-bump/commit/d9cc01f80a308126a00f50a09232a1a88626d54b)
- Pacify linter by Carsten Igel [29868d3](https://github.com/carstencodes/pdm-bump/commit/29868d3c44530a918ed2029ca9ea30097778b94f)
- Pacify mypy by Carsten Igel [5a308ca](https://github.com/carstencodes/pdm-bump/commit/5a308ca3a6bb117d06956de53a51bf1b8bb783d3)
- Fulfilled various tasks by Carsten Igel [b4063c7](https://github.com/carstencodes/pdm-bump/commit/b4063c7fbd28cfe12bfaef645b20582c237b08ca)
- Updated dependencies eager by Carsten Igel [4de6b67](https://github.com/carstencodes/pdm-bump/commit/4de6b67efbd32793464d81b31079f81611074766)
- Run modernization via pyupgrade by Carsten Igel [d3af7f6](https://github.com/carstencodes/pdm-bump/commit/d3af7f6c85ef56cd0668b5d5326dd94fa9116d30)
- Code style by Carsten Igel [6bd85b6](https://github.com/carstencodes/pdm-bump/commit/6bd85b6b319e8c6d5ff3fd6fae91bd397bfaaad5)
- Removed unused imports by Carsten Igel [c9dcada](https://github.com/carstencodes/pdm-bump/commit/c9dcada2dae7e9b23a56506917ac1efcf9840ac9)
- Updated dev revision by Carsten Igel [e2763d8](https://github.com/carstencodes/pdm-bump/commit/e2763d8dda7ce20c4c44ad07bd2896c904b17e6b)
- Re-formatted tests by Carsten Igel [9f4972c](https://github.com/carstencodes/pdm-bump/commit/9f4972c85b2e627f01f88d1ecae279e3ecc17600)
- Multi-line undone by Carsten Igel [707ca7d](https://github.com/carstencodes/pdm-bump/commit/707ca7d7573461505ad42fa13054714e50d5eaa3)
- Some small refactorings by Carsten Igel [1670c04](https://github.com/carstencodes/pdm-bump/commit/1670c041b320ce06630c3f8c2c73b1445482865d)
- Updated 4 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [c2ab47b](https://github.com/carstencodes/pdm-bump/commit/c2ab47bbbc841fcc1a286711d5c90c3127809532)
- Updated 5 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [25ee6c7](https://github.com/carstencodes/pdm-bump/commit/25ee6c7d0254e4259b1d7ad0a985d28d41d12a88)
- Updated 3 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [5575afd](https://github.com/carstencodes/pdm-bump/commit/5575afd91ce02b5069c5d9ff3daf63d42fd805d8)
- Updated 3 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [93bdfb4](https://github.com/carstencodes/pdm-bump/commit/93bdfb400962b6c7f60ae053e145f2279a4f93bc)
- Updated 1 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [602b976](https://github.com/carstencodes/pdm-bump/commit/602b9762e1121adb30c2ca346253ba571c633c21)
- Updated 5 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [f54539b](https://github.com/carstencodes/pdm-bump/commit/f54539b9eb0e8cb4cafbd3707ff7b84719b80338)
- Updated 6 dependencies in pdm.lock by carstencodes (Github Workflow - Auto update) [ce7b87e](https://github.com/carstencodes/pdm-bump/commit/ce7b87e90d3259a5f3ca16f36e3e6c94157bc6e1)
- Updated copyright headers by Carsten Igel [48ccd6e](https://github.com/carstencodes/pdm-bump/commit/48ccd6eccae9141c03bac69766b688cb70a83a66)
- PEP582 rejected by Carsten Igel [ba4d436](https://github.com/carstencodes/pdm-bump/commit/ba4d436f66ec4af7706e2796023413a2af262a3a)
- Added pep8-naming check by Carsten Igel [5c3672a](https://github.com/carstencodes/pdm-bump/commit/5c3672a7585fda3bb0308224909e98193cc67a08)
- Refactor logging, version and config by Carsten Igel [cd11986](https://github.com/carstencodes/pdm-bump/commit/cd1198641584574c633eb494c7c3be67458ac528)
- Refactor Actions by Carsten Igel [eb55ace](https://github.com/carstencodes/pdm-bump/commit/eb55ace1f212a084d30968063b1c9bbab7b3ff0d)
- Fixed unit test for agrparse by Carsten Igel [4ab7aff](https://github.com/carstencodes/pdm-bump/commit/4ab7aff69ae3defb2ef465a3a97ad2572464c859)
- Fixed various issues due to linters by Carsten Igel [91a382b](https://github.com/carstencodes/pdm-bump/commit/91a382bb871eca93771cd2e130989259f2e6fa9f)
- Refactoring for vcs commands by Carsten Igel [b4b0b5d](https://github.com/carstencodes/pdm-bump/commit/b4b0b5d1905220513d632ec6b4b1c0e5fc28354f)
- Formatting by Carsten Igel [0fd2b38](https://github.com/carstencodes/pdm-bump/commit/0fd2b38bf8322144e4f6f4bee549a6d15f08394a)
- Moved tagging to actions by Carsten Igel [cf1716b](https://github.com/carstencodes/pdm-bump/commit/cf1716b27eb7401aa2fdc7a17cb6b891130f6e22)
- Tagging enabled again by Carsten Igel [d6482e0](https://github.com/carstencodes/pdm-bump/commit/d6482e045f7ed3ef3e6b85326c6b1033a4ea8b85)
- Prepare next release by Carsten Igel [34e1226](https://github.com/carstencodes/pdm-bump/commit/34e122634b92a45e251488a754178e989b87d391)
- Re-formatted code by Carsten Igel [c30a443](https://github.com/carstencodes/pdm-bump/commit/c30a44346ab37d4bf964e12661d7d29b5b3cfc32)

### Testing

- Added configuration for code climate cli by Carsten Igel [9c9386f](https://github.com/carstencodes/pdm-bump/commit/9c9386fb970e28cec735afb46dc2d30317bf85d7)
- Added static analysis tools (draft) by Carsten Igel [71a31e1](https://github.com/carstencodes/pdm-bump/commit/71a31e16b0314aa1af1a29cafd358c968774a1ff)
- New interface by Carsten Igel [b047ea2](https://github.com/carstencodes/pdm-bump/commit/b047ea21ad842cc45019f06ff7b1d0cc96977dea)


**Full changelog**: [v0.6.12.post1...v0.7.0a1](https://github.com/carstencodes/pdm-bump/compare/v0.6.12.post1...v0.7.0a1)


##  Changelog for release 0.6.12.post1
Released on 2023-01-09


### Bug Fixes

- Typofixes and wording improvements by Colin Marquardt [fc17b28](https://github.com/carstencodes/pdm-bump/commit/fc17b28fc20a9334eeafedfdbe0db6df15c5b4e3)
- TypeError when using dynamic version by Carsten Igel [d7167e8](https://github.com/carstencodes/pdm-bump/commit/d7167e8322ad8878585ad69e554fdf7e2dc31e4a)

### Build recipes

- Breaking change in git-cliff by Carsten Igel [dfa6024](https://github.com/carstencodes/pdm-bump/commit/dfa6024b3240df982c0e064c12f365e64687a2a6)
- Breaking change in git-cliff by Carsten Igel [ade657a](https://github.com/carstencodes/pdm-bump/commit/ade657a71968e6bff4bd5c4644b1fcb0603ea88c)

### Miscellaneous Tasks

- Updated dependencies to latest revision by Carsten Igel [f439f12](https://github.com/carstencodes/pdm-bump/commit/f439f12af5d0469bf5d1e6adfa11e98a35ce4990)
- Updated dependencies to latest revision by Carsten Igel [b03e5d0](https://github.com/carstencodes/pdm-bump/commit/b03e5d0ab7f78a3531b1797d9a59a5759ecc049a)
- Typofixes and wording improvements by Carsten Igel [af8fd3e](https://github.com/carstencodes/pdm-bump/commit/af8fd3e1766a82ad44378d1a85ef723938fa80e8)
- Prepare next version by Carsten Igel [d7d853f](https://github.com/carstencodes/pdm-bump/commit/d7d853fd371fc03b7ef25fb0cf6e446e359c3a01)
- Prepare next version by Carsten Igel [70c2019](https://github.com/carstencodes/pdm-bump/commit/70c2019c834ce0ccea73eac95bf0aedc60e731a3)
- Prepare next release by Carsten Igel [88edc38](https://github.com/carstencodes/pdm-bump/commit/88edc38697341a3025a2dc6e466d5ef66e372ca2)
- Prepare next release by Carsten Igel [2454adb](https://github.com/carstencodes/pdm-bump/commit/2454adb7fd83fbe28c5dc033cc2c69551d2d96d4)


**Full changelog**: [...v0.6.12.post1](https://github.com/carstencodes/pdm-bump/compare/...v0.6.12.post1)


<!-- generated by git-cliff -->
```

`git cliff -- v0.6.11...v0.7.0` 

```markdown
# Changelog

All notable changes to this project will be documented in this file.

## [0.7.0] - 2023-04-14

### Bug Fixes

- Removed typo
- Do not double define dict
- Removed double argument

### Features

- Added auto-loading
- Enabled verbose logging
- Improved changelog generation
- Finalize explicit version setting

### Miscellaneous Tasks

- Updated 2 dependencies in pdm.lock
- Updated 2 dependencies in pdm.lock
- Updated alpha version
- Refactor allowed parameters
- Refactored argument creation
- Applied format
- Pulled attributes up
- Renamed factory
- Loader instance will be final
- Added configuration after PDM update
- Prepare next alpha
- Prepare release

### Qa

- Modified imports from extension commands

## [0.7.0a1] - 2023-04-10

### Bug Fixes

- Ignore arguments from pdm
- Types are not returned

### Features

- Added actions package
- Added ability to set version explicitly
- Added ability to set version explicitly

### Miscellaneous Tasks

- Updated settings
- Update dependencies
- Use PDM 2.4.7
- Development version
- Fixed linter
- Update linter rule
- Pacify linter
- Pacify linter
- Pacify mypy
- Fulfilled various tasks
- Updated dependencies eager
- Run modernization via pyupgrade
- Code style
- Removed unused imports
- Updated dev revision
- Re-formatted tests
- Multi-line undone
- Some small refactorings
- Updated 4 dependencies in pdm.lock
- Updated 5 dependencies in pdm.lock
- Updated 3 dependencies in pdm.lock
- Updated 3 dependencies in pdm.lock
- Updated 1 dependencies in pdm.lock
- Updated 5 dependencies in pdm.lock
- Updated 6 dependencies in pdm.lock
- Updated copyright headers
- PEP582 rejected
- Added pep8-naming check
- Refactor logging, version and config
- Refactor Actions
- Fixed unit test for agrparse
- Fixed various issues due to linters
- Refactoring for vcs commands
- Formatting
- Moved tagging to actions
- Tagging enabled again
- Prepare next release
- Re-formatted code

### Build

- Added autoflake to formatters
- Set fixed revision
- Added Automatic update
- Repaired auto-complete workflow
- Repaired auto-complete workflow
- Fixed auto update
- Fixed auto update
- Fix gitlint error during update
- Fix gitlint error during update
- Set job names
- Added clean-up routine
- Add clean-up script

### Qa

- Added configuration for code climate cli
- Added static analysis tools (draft)
- New interface

## [0.6.12.post1] - 2023-01-09

### Bug Fixes

- Typofixes and wording improvements
- TypeError when using dynamic version

### Miscellaneous Tasks

- Updated dependencies to latest revision
- Updated dependencies to latest revision
- Typofixes and wording improvements
- Prepare next version
- Prepare next version
- Prepare next release
- Prepare next release

### Build

- Breaking change in git-cliff
- Breaking change in git-cliff

<!-- generated by git-cliff -->
```

**Software information**

- Operating system: Linux notebook-carsten 5.19.0-38-generic # 39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Rust version: rustc 1.68.0 (2c8cc3432 2023-03-06)
- Project version: 1.1.2

**Additional context**

Changelog Configuration:

```toml
# configuration file for git-cliff (0.1.0)

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ##  Changelog for release {{ version | trim_start_matches(pat="v") }}
{% else %}\
    ## [unreleased]
{% endif %}\

   Released on {{ timestamp | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }} by {{ commit.author.name }} [{{ commit.id| truncate(length=7, end="")}}](https://github.com/carstencodes/pdm-bump/commit/{{ commit.id }})\
    {% endfor %}
{% endfor %}\n
{% if version %}\
{% if previous %}\
**Full changelog**: [{{ previous.version }}...{{ version }}](https://github.com/carstencodes/pdm-bump/compare/{{ previous.version }}...{{ version }})
{% endif %}\n
{% endif %}\
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/orhun/git-cliff/issues/${2}))"},
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^doc", group = "Documentation"},
    { message = "^docs", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Refactored"},
    { message = "^style", group = "Styling"},
    { message = "^test", group = "Testing"},
    { message = "^qa", group = "Testing"},
    { message = "^chore\\(release\\): prepare for", skip = true},
    { message = "^ci", group = "Integration Tasks" },
    { message = "^build", group = "Build recipes" },
    { message = "^chore", group = "Miscellaneous Tasks"},
    { body = ".*security", group = "Security"},
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# regex for skipping tags
skip_tags = "v0.1.0-beta.1"
# regex for ignoring tags
ignore_tags = ""
# sort the tags chronologically
date_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42

```

**Comment by orhun** [comment]
Can you share how you use `git-cliff` inside `pyproject.toml` as well? It should be `[tool.git-cliff.<section>]` instead of `[tool.gitcliff.<section>]`.

**Comment by carstencodes** [comment]
Here is my pyproject.toml file:

```toml
# configuration file for git-cliff (0.1.0)

[tool.git-cliff.changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ##  Changelog for release {{ version | trim_start_matches(pat="v") }}
{% else %}\
    ## [unreleased]
{% endif %}\

   Released on {{ timestamp | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }} by {{ commit.author.name }} [{{ commit.id| truncate(length=7, end="")}}](https://github.com/carstencodes/pdm-bump/commit/{{ commit.id }})\
    {% endfor %}
{% endfor %}\n
{% if version %}\
{% if previous %}\
**Full changelog**: [{{ previous.version }}...{{ version }}](https://github.com/carstencodes/pdm-bump/compare/{{ previous.version }}...{{ version }})
{% endif %}\n
{% endif %}\
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[tool.git-cliff.git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/orhun/git-cliff/issues/${2}))"},
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^doc", group = "Documentation"},
    { message = "^docs", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Refactored"},
    { message = "^style", group = "Styling"},
    { message = "^test", group = "Testing"},
    { message = "^qa", group = "Testing"},
    { message = "^chore\\(release\\): prepare for", skip = true},
    { message = "^ci", group = "Integration Tasks" },
    { message = "^build", group = "Build recipes" },
    { message = "^chore", group = "Miscellaneous Tasks"},
    { body = ".*security", group = "Security"},
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# regex for skipping tags
skip_tags = "v0.1.0-beta.1"
# regex for ignoring tags
ignore_tags = ""
# sort the tags chronologically
date_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# limit the number of commits included in the changelog.
# limit_commits = 42
```

Neither  `git cliff --  v0.6.11..v0.7.0` nor  `git cliff --config pyproject.toml --  v0.6.11..v0.7.0` produce the correct output. The output is 

```markdown
## [0.7.0] - 2023-04-14

### Chore

- Updated 2 dependencies in pdm.lock
- Updated 2 dependencies in pdm.lock
- Updated alpha version
- Refactor allowed parameters
- Refactored argument creation
- Applied format
- Pulled attributes up
- Renamed factory
- Loader instance will be final
- Added configuration after PDM update
- Prepare next alpha
- Prepare release

### Feat

- Added auto-loading
- Enabled verbose logging
- Improved changelog generation
- Finalize explicit version setting

### Fix

- Removed typo
- Do not double define dict
- Removed double argument

### Qa

- Modified imports from extension commands

## [0.7.0a1] - 2023-04-10

### Build

- Added autoflake to formatters
- Set fixed revision
- Added Automatic update
- Repaired auto-complete workflow
- Repaired auto-complete workflow
- Fixed auto update
- Fixed auto update
- Fix gitlint error during update
- Fix gitlint error during update
- Set job names
- Added clean-up routine
- Add clean-up script

### Chore

- Updated settings
- Update dependencies
- Use PDM 2.4.7
- Development version
- Fixed linter
- Update linter rule
- Pacify linter
- Pacify linter
- Pacify mypy
- Fulfilled various tasks
- Updated dependencies eager
- Run modernization via pyupgrade
- Code style
- Removed unused imports
- Updated dev revision
- Re-formatted tests
- Multi-line undone
- Some small refactorings
- Updated 4 dependencies in pdm.lock
- Updated 5 dependencies in pdm.lock
- Updated 3 dependencies in pdm.lock
- Updated 3 dependencies in pdm.lock
- Updated 1 dependencies in pdm.lock
- Updated 5 dependencies in pdm.lock
- Updated 6 dependencies in pdm.lock
- Updated copyright headers
- PEP582 rejected
- Added pep8-naming check
- Refactor logging, version and config
- Refactor Actions
- Fixed unit test for agrparse
- Fixed various issues due to linters
- Refactoring for vcs commands
- Formatting
- Moved tagging to actions
- Tagging enabled again
- Prepare next release
- Re-formatted code

### Feat

- Added actions package
- Added ability to set version explicitly
- Added ability to set version explicitly

### Fix

- Ignore arguments from pdm
- Types are not returned

### Qa

- Added configuration for code climate cli
- Added static analysis tools (draft)
- New interface

## [0.6.12.post1] - 2023-01-09

### Build

- Breaking change in git-cliff
- Breaking change in git-cliff

### Chore

- Updated dependencies to latest revision
- Updated dependencies to latest revision
- Typofixes and wording improvements
- Prepare next version
- Prepare next version
- Prepare next release
- Prepare next release

### Fix

- Typofixes and wording improvements
- TypeError when using dynamic version
```

On stderr the following output is presented:

` WARN  git_cliff > Changelog body is not specified, using the default template.`

I would expect `Qa` to be `Testing` etc.
