### ISSUE TITLE
Allow define sort on cliff.toml

### ISSUE THREAD

**Issue by robsonpeixoto** [orhun/git-cliff#31]
**Is your feature request related to a problem? Please describe.**

Is not a problem, but is easier to share `cliff.toml` with all required config than share the file and ask people to pass the sort parameter when run.

**Comment by orhun** [comment]
I implemented this in 4eb334da06c1bde3b53d95ea50d086daab07e4bb. Now you can define the following values in the configuration file:

```toml
[git]
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
```

These changes will be available with the upcoming release so feel free to try it out and report bugs by either pulling the [docker image](https://hub.docker.com/repository/docker/orhunp/git-cliff) or [building from source](https://github.com/orhun/git-cliff/#build-from-source).
