### ISSUE TITLE
Multiline matches with CR (^M) characters

### ISSUE THREAD

**Issue by wookayin** [orhun/git-cliff#423]
**Describe the bug**

I think only the title of git commit messages should be considered, but when the commit contains mixed CR/LF for some reason, extraction of commit title would be broken, resulting into multi-line messages (with CR) printed in the release note.

**To reproduce**

```
git clone https://github.com/neovim/neovim
git cliff -c c.toml 72a6643b1~1..ca5de93
```

c.toml:
```toml
[git]
conventional_commits = true
filter_unconventional = false
filter_commits = false
commit_parsers = [
    { message = "^.*", group = "Others" },
]

[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits%}\
       - <<< {{ commit.id }} >>> {{ commit.message | upper_first }}
    {% endfor %}\
{% endfor %}\n
"""
```

Output:

```

### Others
- <<< 72a6643b1380cdf6f1153d70eeaffb90bdca30d6 >>> Docs #24061

- nvim requires rpc responses in reverse order. https://github.com/neovim/neovim/issues/19932
- NVIM_APPNAME: UIs normally should NOT set this.^M
^M
ref #23520^M
fix #24050^M
fix #23660^M
fix #23353^M
fix #23337^M
fix #22213^M
fix #19161^M
fix #18088^M
fix #20693
- <<< ca5de9306c00d07cce1daef1f0038c937098bc66 >>> Inlay hints #23984

```

A strange commit [72a6643b1380cdf6f1153d70eeaffb90bdca30d6](https://github.com/neovim/neovim/commit/72a6643b1380cdf6f1153d70eeaffb90bdca30d6) has a commit message where CR and LF is mixed.

**Expected behavior**

Only the first line is considered. Maybe we should normalize CR, LF into LF.

**Screenshots / Logs**

N/A

**Software information**

- Operating system: macos
- Rust version: 1.70
- Project version: 1.4.0

**Additional context**

This repro is a simplification of https://github.com/neovim/neovim/pull/26818 where `git cliff --config scripts/cliff.toml v0.9.0..HEAD` produces some strange multi-line release note items.
