### ISSUE TITLE
Allow use of environment variables in replace_command 

### ISSUE THREAD

**Issue by Cyclonit** [orhun/git-cliff#610]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

The [documentation of commit_parsers](https://git-cliff.org/docs/configuration/git#commit_preprocessors) has an example using an environment variable `$COMMIT_SHA`. This variable is set explicitly in [commit.rs:231](https://github.com/orhun/git-cliff/blob/main/git-cliff-core/src/commit.rs#L231). `changelog.postprocessors` do not have access to any environment variables.

### Desired solution

The shells used for `replace_command` should inherit all environment variables from the git-cliff process, such that they can be used in `replace_command`.

### Alternatives considered

None

**Comment by orhun** [comment]
I gave this a try again, with the following scenario:

```toml
postprocessors = [
  { pattern = '<REPO>', replace_command = 'echo "$CI_PROJECT_URL"' },
]
```

Then use `<REPO>` somewhere in `body`.

Afterwards:

```sh
$ export CI_PROJECT_URL='github.com/git-cliff'

$ git cliff # actually replaces
```

I think my assumption at Discord was wrong yesterday. Since we are spawning a shell (`sh/`cmd`), the environment variables are actually present.

Can you give this a try again?

**Comment by Cyclonit** [comment]
You are right, this does work properly already.

**Comment by b-heimann-senacor** [comment]
> I gave this a try again, with the following scenario:
> 
> postprocessors = [
>   { pattern = '<REPO>', replace_command = 'echo "$CI_PROJECT_URL"' },
> ]
> Then use `<REPO>` somewhere in `body`.

@orhun This does not work in **git-cliff 2.10.0**.

```toml
postprocessors = [
  # Replace the placeholders with a URL.
  { pattern = '<REPO>', replace_command = 'echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"' }
]
```

When I execute

```bash
git-cliff --verbose --latest
```

I expect to get the changelog of the latest release, but it only outputs this:

```bash
# Changelog

All notable changes to this project will be documented in this file.
https://github.com/my-github-org/my-repository
```

Is this a bug?

Edit:

I found out that it works this way, but it's not documented anywhere and it's very confusing:

```toml
postprocessors = [
  # Replace the placeholders with a URL.
  { pattern = '<REPO>', replace_command = 'sed "s|<REPO>|${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}|g"' }
]
```

**Comment by orhun** [comment]
Hey @b-heimann-senacor 

I'm really confused by your use case.  Are you trying to dynamically replace the `<REPO>` variable in the changelog or trying to do something else? Can you share your template?

That sed command also seems odd...

**Comment by b-heimann-senacor** [comment]
Hi @orhun,

I want to use a single **cliff.toml** configuration file to generate changelogs for multiple GitHub repositories. 

In GitHub Actions, you can get the repository URL for the current repository via environment variables:

```bash
echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
```

I'm using a simplified version of the cliff.toml that is used by [git-cliff](https://github.com/orhun/git-cliff/blob/main/cliff.toml) itself. The only relevant difference is that the `<REPO>` postprocessor uses `replace_command` instead of `replace`:

```toml
# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/docs/#introduction
header = """
# Changelog\n
All notable changes to this project will be documented in this file.
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% macro print_commit(commit) -%}
    - {% if commit.scope %}<ins>{{ commit.scope }}</ins> - {% endif %}{{ commit.message | upper_first }}\
{% endmacro -%}

{% if version %}
    ## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = [
  # Replace the placeholders with a URL.
  { pattern = '<REPO>', replace_command = 'echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"' },
]

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
  # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" },
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
  { message = "!: ", group = "<!-- 0 -->BREAKING CHANGES" },
  { message = "^feat", group = "<!-- 1 -->New Features" },
  { message = "^fix", group = "<!-- 2 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^doc", group = "<!-- 4 -->Documentation" },
  { message = "^chore\\(deps.*\\)", scope = "", group = "<!-- 5 -->Dependency Upgrades" },
  { message = "^style|^refactor|^test|^ci", group = "<!-- 6 -->Technical Enhancements" },
  { message = "^revert", group = "<!-- 7 -->Revert" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = true
# Regex to select git tags that represent releases.
tag_pattern = "v?[0-9].*"
```

I generate the changelog locally using

```bash
export GITHUB_SERVER_URL="https://github.com" 
export GITHUB_REPOSITORY="my-github-org/my-repository"   
git-cliff --verbose --output CHANGELOG.md
```

With the above configuration, it doesn't work, but if I use the following `replace_command`, it works as expected. The sed command is just the standard way to [search and replace](https://unix.stackexchange.com/questions/382077/replace-a-string-including-a-slash-using-sed-command):

```toml
postprocessors = [
  # Replace the placeholders with a URL.
  { pattern = '<REPO>', replace_command = 'sed "s|<REPO>|${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}|g"' },
]
```

Apparently, git-cliff passes the **entire release body** to the `replace_command` and replaces it with the command's output. However, what I don't understand is why it ignores the pattern. I would expect it to only replace occurrences of the pattern.
