### ISSUE TITLE
Entire env output if `env` included in commit message

### ISSUE THREAD

**Issue by AlecRust** [orhun/git-cliff#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Our release process involves a PR being created by GitHub Actions with the version bump and changelog created via git-cliff.

During this process git-cliff runs twice, once to build the `CHANGELOG.md` and once to build the release notes for the latest release, which are included in the release PR:

```yml
- name: Update CHANGELOG.md
  uses: orhun/git-cliff-action@v3
  with:
      config: .cliff/changelog-md.toml
      args: --tag ${{ steps.set_new_version.outputs.new_version }}
  env:
      OUTPUT: CHANGELOG.md
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Commit changes
  run: |
      git commit -am "chore(release): ${{ steps.set_new_version.outputs.new_version }}"

- name: Build release notes
  uses: orhun/git-cliff-action@v3
  id: git-cliff
  with:
      config: .cliff/github-changes.toml
      args: --unreleased
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Create Pull Request
  env:
      GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  run: |
      git push origin ${{ steps.set_branch.outputs.release_branch }}
      gh pr create --title "Release ${{ steps.set_new_version.outputs.new_version }}" \
      --body-file - \
      --label "release" <<EOF
      This PR prepares new release **${{ steps.set_new_version.outputs.new_version }}**. Please review the changes below.

      ## Release Notes
      ${{ steps.git-cliff.outputs.content }}

      ---
```

After merging a PR (with merge commit) that included commits with these messages:

- refactor: move `config.platformUrl` to the `env` package and update its usage
- chore(PRD-1234): update `Button` and `Link` building blocks to allow blah blah
- chore(PRD-1234): ensure the navigation bar uses full urls and enforces blah blah

The release notes in the release PR seems to include the `env` output of the GitHub runner i.e.

```md
## Release Notes

### 🐛 Bug Fixes

* **(PRD-1234)** Add missing parameter #1293

### 🛠️ Refactor

* Move  to the SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
CONDA=/usr/share/miniconda
GITHUB_WORKSPACE=/home/runner/work/our-repo/our-repo
JAVA_HOME_11_X64=/usr/lib/jvm/temurin-11-jdk-amd64
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_69795f54-9477-4db4-96e5-4b62703763d1
GITHUB_ACTION=__run_5
JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
GITHUB_RUN_NUMBER=35
RUNNER_NAME=GitHub Actions 16
GRADLE_HOME=/usr/share/gradle-8.7
GITHUB_REPOSITORY_OWNER_ID=86711234
ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE=/opt/actionarchivecache
XDG_CONFIG_HOME=/home/runner/.config
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
ANT_HOME=/usr/share/ant
GH_TOKEN=ghp_REMOVED
JAVA_HOME_8_X64=/usr/lib/jvm/temurin-8-jdk-amd64
GITHUB_TRIGGERING_ACTOR=username
GITHUB_REF_TYPE=branch
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650
ANDROID_NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653
BOOTSTRAP_HASKELL_NONINTERACTIVE=1
PWD=/home/runner/work/our-repo/our-repo
PIPX_BIN_DIR=/opt/pipx_bin
STATS_TRP=true
GOROOT_1_20_X64=/opt/hostedtoolcache/go/1.20.14/x64
GITHUB_REPOSITORY_ID=397998388
DEPLOYMENT_BASEPATH=/opt/runner
GITHUB_ACTIONS=true
STATS_VMD=true
ANDROID_NDK_LATEST_HOME=/usr/local/lib/android/sdk/ndk/26.3.11579264
SYSTEMD_EXEC_PID=470
GITHUB_SHA=2b926bb32bebdd92c38a8a8a1127a41494d54037
GITHUB_WORKFLOW_REF=username/our-repo/.github/workflows/prepare-release.yml@refs/heads/main
POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-ubuntu22
RUNNER_ENVIRONMENT=github-hosted
STATS_EXTP=https://provjobdsettingscdn.blob.core.windows.net/settings/provjobdsettings-0.5.172+1/provjobd.data
DOTNET_MULTILEVEL_LOOKUP=0
STATS_TIS=mining
GITHUB_REF=refs/heads/main
RUNNER_OS=Linux
GITHUB_REF_PROTECTED=true
HOME=/home/runner
GITHUB_API_URL=https://api.github.com
LANG=C.UTF-8
RUNNER_TRACKING_ID=github_4398fa9d-f975-43e2-9cc4-93eafcb039cb
RUNNER_ARCH=X64
GOROOT_1_21_X64=/opt/hostedtoolcache/go/1.21.9/x64
RUNNER_TEMP=/home/runner/work/_temp
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_69795f57-9477-4db4-98e5-4b62703763d1
EDGEWEBDRIVER=/usr/local/share/edge_driver
JAVA_HOME_21_X64=/usr/lib/jvm/temurin-21-jdk-amd64
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_69495f50-9477-4db4-98e5-4b62703763d1
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
INVOCATION_ID=7c31654b03484391b41d76668ab65b9a
STATS_D=false
GITHUB_EVENT_NAME=workflow_dispatch
GITHUB_RUN_ID=9076740854
JAVA_HOME_17_X64=/usr/lib/jvm/temurin-17-jdk-amd64
ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_69795f57-9477-4db4-98e5-4b62703763d1
HOMEBREW_NO_AUTO_UPDATE=1
GITHUB_ACTOR=username
NVM_DIR=/home/runner/.nvm
SGX_AESM_ADDR=1
GITHUB_RUN_ATTEMPT=1
STATS_RDCL=true
ANDROID_HOME=/usr/local/lib/android/sdk
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
RUNNER_USER=runner
ACCEPT_EULA=Y
STATS_UE=true
USER=runner
GITHUB_SERVER_URL=https://github.com
STATS_V3PS=true
PIPX_HOME=/opt/pipx
GECKOWEBDRIVER=/usr/local/share/gecko_driver
STATS_EXT=true
CHROMEWEBDRIVER=/usr/local/share/chromedriver-linux64
SHLVL=0
ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg
GITHUB_ACTOR_ID=1131604
RUNNER_TOOL_CACHE=/opt/hostedtoolcache
ImageVersion=20240422.1.0
DOTNET_NOLOGO=1
GITHUB_WORKFLOW_SHA=2b926bg32bebdd92c38h8a8a1127a41494d54037
GITHUB_REF_NAME=main
GITHUB_JOB=prepare-release
XDG_RUNTIME_DIR=/run/user/1001
AZURE_EXTENSION_DIR=/opt/az/azcliextensions
PERFLOG_LOCATION_SETTING=RUNNER_PERFLOG
STATS_VMFE=true
GITHUB_REPOSITORY=username/our-repo
GOROOT_1_22_X64=/opt/hostedtoolcache/go/1.22.2/x64
ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/25.2.9519653
CHROME_BIN=/usr/bin/google-chrome
GITHUB_RETENTION_DAYS=90
JOURNAL_STREAM=8:18687
RUNNER_WORKSPACE=/home/runner/work/web-ng
LEIN_HOME=/usr/local/lib/lein
LEIN_JAR=/usr/local/lib/lein/self-installs/leiningen-2.11.2-standalone.jar
GITHUB_ACTION_REPOSITORY=
PATH=/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
RUNNER_PERFLOG=/home/runner/perflog
GITHUB_BASE_REF=
GHCUP_INSTALL_BASE_PREFIX=/usr/local
CI=true
SWIFT_PATH=/usr/share/swift/usr/bin
ImageOS=ubuntu22
STATS_D_D=false
GITHUB_REPOSITORY_OWNER=username
GITHUB_HEAD_REF=
GITHUB_ACTION_REF=
GITHUB_WORKFLOW=Prepare Release
DEBIAN_FRONTEND=noninteractive
GITHUB_OUTPUT=/home/runner/work/_temp/_runner_file_commands/set_output_69795f50-9477-4db4-98e5-4b62703763d1
AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
_=/usr/bin/env package and update its usage e93fab3
* **(PRD-2896)** Use  component on navbar instead of a native anchor tag b5ab0a7
* **(PRD-2896)** Rename  to  f31d7a2

### 🧪 Testing

* **(PRD-2896)** Fix  unit tests and update snapshot 4fab3c5
```

It seems the "refactor: move `config.platformUrl` to the `env` package and update its usage" commit has resulted in `env` being output into the changelog.

Interestingly this only happened in the release notes for the PR description, the full build of the `CHANGELOG.md` was fine:

```md
## [2024.5.15](https://github.com/username/our-repo/compare/2024.5.14...2024.5.15) - 14 May 2024

### 🐛 Bug Fixes

* **(PRD-2896)** Add missing parameter (#1893)

### 🛠️ Refactor

* Move `config.platformUrl` to the `env` package and update its usage
* **(PRD-1234)** Use `Link` component on navbar instead of a native anchor tag
* **(PRD-1234)** Rename `useAnchorTag` to `forcePageReload`

### 🧪 Testing

* **(PRD-1234)** Fix `Navbar` unit tests and update snapshot
```

Here is the config for the full `CHANGELOG.md` build:

`.cliff/changelog-md.toml`
```toml
# git-cliff config file for building CHANGELOG.md
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "username"
repo = "our-repo"

[changelog]
# Changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.
"""
# Changelog body in Markdown format
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
	\n## [{{ version }}]({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}) - {{ timestamp | date(format="%e %B %Y") }}
{% else %}\
	\n## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
	### {{ group | striptags | trim | upper_first }}
	{% for commit in commits %}
		* {% if commit.scope %}**({{ commit.scope }})** {% endif %}\
			{{ commit.message | upper_first | trim }}\
			{% if commit.github.pr_number %} \
				([#{{ commit.github.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.github.pr_number }}))\
			{% else %} \
				([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
			{% endif %}\
	{% endfor %}
{% endfor %}
{%- macro remote_url() -%}
	https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""

[git]
# Preprocess the commit messages
commit_preprocessors = [
	# Remove PR numbers from commits
	{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

# Parse and group commits
commit_parsers = [
	{ message = "^chore\\(release\\)", skip = true },
	{ message = '^(chore|fix|build)\(deps\):', group = "<!-- 99 -->📦️ Dependencies", scope = "" },
	{ message = "^feat", group = "<!-- 0 -->🚀 Features" },
	{ message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
	{ message = "^doc", group = "<!-- 2 -->📚 Documentation" },
	{ message = "^perf", group = "<!-- 3 -->⚡ Performance" },
	{ message = "^refactor", group = "<!-- 4 -->🛠️ Refactor" },
	{ message = "^style", group = "<!-- 5 -->🎨 Styling" },
	{ message = "^test", group = "<!-- 6 -->🧪 Testing" },
	{ message = "^chore|^ci|^build", group = "<!-- 8 -->⚙️ Miscellaneous" },
	{ body = ".*security", group = "<!-- 9 -->🛡️ Security" },
	{ message = "^revert", group = "<!-- 10 -->◀️ Revert" },
]
```

Here is the config for the latest release notes where the problem occurred:

`.cliff/github-changes.toml`
```toml
# git-cliff config file for building GitHub release notes
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "username"
repo = "our-repo"

[changelog]
# Changelog body in Markdown format
# https://keats.github.io/tera/docs/#introduction
body = """
{% for group, commits in commits | group_by(attribute="group") %}
	### {{ group | striptags | trim | upper_first }}
	{% for commit in commits %}
		* {% if commit.scope %}**({{ commit.scope }})** {% endif %}\
			{{ commit.message | upper_first | trim }}\
			{% if commit.github.pr_number %} \
				#{{ commit.github.pr_number }}\
			{% else %} \
				{{ commit.id | truncate(length=7, end="") }}\
			{% endif %}\
	{% endfor %}
{% endfor %}
{%- macro remote_url() -%}
	https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""

[git]
# Preprocess the commit messages
commit_preprocessors = [
	# Remove PR numbers from commits
	{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

# Parse and group commits
commit_parsers = [
	{ message = "^chore\\(release\\)", skip = true },
	{ message = '^(chore|fix|build)\(deps\):', group = "<!-- 99 -->📦️ Dependencies", scope = "" },
	{ message = "^feat", group = "<!-- 0 -->🚀 Features" },
	{ message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
	{ message = "^doc", group = "<!-- 2 -->📚 Documentation" },
	{ message = "^perf", group = "<!-- 3 -->⚡ Performance" },
	{ message = "^refactor", group = "<!-- 4 -->🛠️ Refactor" },
	{ message = "^style", group = "<!-- 5 -->🎨 Styling" },
	{ message = "^test", group = "<!-- 6 -->🧪 Testing" },
	{ message = "^chore|^ci|^build", group = "<!-- 8 -->⚙️ Miscellaneous" },
	{ body = ".*security", group = "<!-- 9 -->🛡️ Security" },
	{ message = "^revert", group = "<!-- 10 -->◀️ Revert" },
]
```

### Steps To Reproduce

1. Add a commit with the message "Move `config.platformUrl` to the `env` package and update its usage"
2. Run git-cliff in GitHub Actions with the `.cliff/github-changes.toml` config provided above
3. See that the entire GitHub runner `env` is output in the release notes

### Expected behavior

I don't expect `env` to be output. `env` is not output with the 

### Software information

I'm running latest git-cliff from https://github.com/orhun/git-cliff-action

**Comment by AlecRust** [comment]
Interestingly this issue did not occur when running against the same `.cliff/github-changes.toml` config when building the GitHub release:

```yml
- name: Build release notes
    uses: orhun/git-cliff-action@v3
    id: git-cliff
    with:
        config: .cliff/github-changes.toml
        args: --latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Create GitHub release
    uses: softprops/action-gh-release@v2
    with:
        body: ${{ steps.git-cliff.outputs.content }}
        tag_name: ${{ steps.set_new_version.outputs.new_version }}
        token: ${{ secrets.DEPLOY_TOKEN }}
```

Resulted in:

```md
### 🐛 Bug Fixes

* **(PRD-1234)** Add missing parameter #1893

### 🛠️ Refactor

* Move `config.platformUrl` to the `env` package and update its usage
* **(PRD-1234)** Use `Link` component on navbar instead of a native anchor tag
* **(PRD-1234)** Rename `useAnchorTag` to `forcePageReload`

### 🧪 Testing

* **(PRD-1234)** Fix `Navbar` unit tests and update snapshot
```

However later in the deploy process the "Slack message" step failed and seemed to be "running the release notes as code" despite the `env` not being output:

**Prepare Slack release notes**
```
Run GIT_CLIFF_NOTES="
  GIT_CLIFF_NOTES="
  *🐛 Bug Fixes*
  
  • *(PRD-1234)* Add missing parameter 
  
  *🛠️ Improvements*
  
  • Move `config.platformUrl` to the `env` package and update its usage 
  • *(PRD-1234)* Use `Link` component on navbar instead of a native anchor tag
  • *(PRD-1234)* Rename `useAnchorTag` to `forcePageReload`
  
  *🧪 Testing Enhancements*
  
  • *(PRD-1234)* Fix `Navbar` unit tests and update snapshot
  • *(PRD-2896)* Fix unit tests that got broken due to changes on `env.publicPlatform`
  # If there is content, pass it through jq to escape characters
  if [[ $GIT_CLIFF_NOTES =~ [^[:space:]] ]]; then
      SLACK_NOTES=$(echo "$GIT_CLIFF_NOTES" | jq -Rs .)
  else
      SLACK_NOTES="Bug fixes and improvements 😉"
  fi
  echo "slack_notes=$SLACK_NOTES" >> $GITHUB_OUTPUT
  echo "Release notes for Slack: $SLACK_NOTES"
  shell: /usr/bin/bash -e {0}
/home/runner/work/_temp/0ace4987-5d2f-41b9-8585-7c8dbf974503.sh: line 15: config.platformUrl: command not found
/home/runner/work/_temp/0ace4987-5d2f-41b9-8585-7c8dbf974503.sh: line 15: Link: command not found
/home/runner/work/_temp/0ace4987-5d2f-41b9-8585-7c8dbf974503.sh: line 15: useAnchorTag: command not found
/home/runner/work/_temp/0ace4987-5d2f-41b9-8585-7c8dbf974503.sh: line 15: forcePageReload: command not found
/home/runner/work/_temp/0ace4987-5d2f-41b9-8585-7c8dbf974503.sh: line 15: Navbar: command not found
/home/runner/work/_temp/0ace4987-5d2f-41b9-8585-7c8dbf974503.sh: line 15: env.publicPlatform: command not found
```

Here are the steps:

```yml
- name: Build Slack release notes
  uses: orhun/git-cliff-action@v3
  id: git-cliff
  with:
      config: .cliff/slack-changes.toml
      args: --latest
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Prepare Slack release notes
  id: prepare_release_notes
  run: |
      GIT_CLIFF_NOTES="${{ steps.git-cliff.outputs.content }}"
      # If there is content, pass it through jq to escape characters
      if [[ $GIT_CLIFF_NOTES =~ [^[:space:]] ]]; then
          SLACK_NOTES=$(echo "$GIT_CLIFF_NOTES" | jq -Rs .)
      else
          SLACK_NOTES="Bug fixes and improvements 😉"
      fi
      echo "slack_notes=$SLACK_NOTES" >> $GITHUB_OUTPUT
      echo "Release notes for Slack: $SLACK_NOTES"

- name: Send message to Slack channel
  uses: slackapi/slack-github-action@v1.26.0
  env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  with:
      channel-id: '1234'
      payload: |
          {
              "text": "Deployed website version ${{ github.ref_name }}",
              "blocks": [
                  {
                      "type": "header",
                      "text": {
                          "type": "plain_text",
                          "text": "Deployed website version ${{ github.ref_name }}"
                      }
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": ${{ steps.prepare_release_notes.outputs.slack_notes }}
                      }
                  }
              ]
          }
```
