### ISSUE TITLE
Format markdown

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#678]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Writing a Tera template with perfect formatting is hard. Tweaking things with `{%-` instead of `{%` and `trim = true` is sometimes annoying.

### Desired solution

`git-cliff` should support outputting the formatted markdown file. e.g.

```toml
[changelog]
# formats the changelog (only supports markdown)
format = true
```

We can use a crate like [`prettify-markdown`](https://crates.io/crates/prettify-markdown) or something similar (and more up-to-date maybe).

We can detect markdown files by simply looking at the extension (`.md`).

### Alternatives considered

Users can always configure [`postprocessors`](https://git-cliff.org/docs/configuration/changelog#postprocessors) to do markdown formatting:

```toml
[changelog]
postprocessors = [
  { pattern = '.*', replace_command = "mdformat -" },
]
```

But I think it is better to support this feature out-of-the-box.
