### ISSUE TITLE
Support overriding the API URL in config

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#704]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Overriding the API URL for remotes is only possible via environment variables, e.g. `GITLAB_API_URL`. This is not very convenient.

This can be doable via config as well.

### Desired solution

```toml
[remote.gitlab]
api_url="https://gitlab.archlinux.org/api/v4"
owner = "archlinux"
repo = "arch-repro-status"
```

### Alternatives considered

None.
