### ISSUE TITLE
(GitHub) Default env vars naming

### ISSUE THREAD

**Issue by mateusz-was** [orhun/git-cliff#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Hi!

This is more 'quality-of-life' enhancement rather than bug, bug I guess it might be helpful...

There are 2 sets naming standards for default GitHub env var values:
1. GitHub CLI values (prefixed `GH_`): https://cli.github.com/manual/gh_help_environment
2. Default env vars set by GitHub in Actions (prefixed `GITHUB_`): https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables

For default repository value git-cliff uses `GITHUB_REPO` which doesn't fall inline with any of the above.
`GH_REPO` is used in 1) and `GITHUB_REPOSITORY` is used in 2)

This can be confusing when you use git-cliff in GitHub Actions for the first time (directly from CLI, without https://github.com/orhun/git-cliff-action).

### Steps To Reproduce

1. Setup GitHub Action pipeline
```
jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: '${{ secrets.GIT_CLIFF_PAT }}'
    - name: Install git-cliff
      run: pip install git-cliff
    - name: Render changelog
      run: |
        env | grep GITHUB
        git cliff -v --github-repo=$GITHUB_REPOSITORY --github-token=${{ secrets.GIT_CLIFF_PAT }}` 
```

### Expected behavior

`--github-repo=$GITHUB_REPOSITORY` should be obsolete and it's value taken from existing `GITHUB_REPOSITORY` default env variable for better user experience

### Software information

- Operating system: GitHub Actions
- Rust version: - (used from PyPI)
- Project version: 2.7.0
